//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESS
    {
        public ACCESS()
        {
            this.EMPLOYEE_ACCESS = new HashSet<EMPLOYEE_ACCESS>();
        }
    
        public int ACC_ID { get; set; }
        public string ACC_NAME { get; set; }
        public string ACC_DESCRIPTION { get; set; }
        public string ACC_CATEGORY { get; set; }
    
        public virtual ICollection<EMPLOYEE_ACCESS> EMPLOYEE_ACCESS { get; set; }
    }
}
