//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PARA_VISITS
    {
        public long ID { get; set; }
        public string IP { get; set; }
        public string PATH_INFO { get; set; }
        public int UTYPE { get; set; }
        public System.DateTime DATE { get; set; }
        public string PROVENANCE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string COUNTRYCODE { get; set; }
        public string COUNTRYNAME { get; set; }
        public string REGIONCODE { get; set; }
        public string REGIONNAME { get; set; }
        public string CITY { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
    }
}
