//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAREERS_MIAMI
    {
        public int CAREERS_MIAMI_ID { get; set; }
        public string CAREERS_MIAMI_DOCUMENT { get; set; }
        public string CAREERS_MIAMI_DOCUMENT_TITLE { get; set; }
        public bool CAREERS_MIAMI_ENGLISH { get; set; }
        public bool CAREERS_MIAMI_ACTIVE { get; set; }
        public Nullable<bool> CAREERS_MIAMI_INTRANET_ACTIVE { get; set; }
    }
}
