//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATION_CE
    {
        public int CERTIFICATION_CE_ID { get; set; }
        public string CERTIFICATION_NAME { get; set; }
        public Nullable<int> CERTIFICATION_PRODUCTLINE { get; set; }
        public Nullable<int> CERTIFICATION_PRODUCT { get; set; }
        public string CERTIFICATION_URL { get; set; }
        public string CERTIFICATION_TEST_URL { get; set; }
        public string CERTIFICATION_TYPE { get; set; }
        public Nullable<int> CERTIFICATION_SIZE { get; set; }
        public Nullable<int> CERTIFICATION_TEST_SIZE { get; set; }
        public Nullable<int> CERTIFICATION_PAGE { get; set; }
        public Nullable<bool> CERTIFICATION_ACTIVE { get; set; }
    }
}
