//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATION_NAME
    {
        public int CERTIFICATION_NAME_ID { get; set; }
        public string CERTIFICATION_NAME1 { get; set; }
        public int CERTIFICATION_NAME_TYPE { get; set; }
        public string CERTIFICATION_NAME_URL { get; set; }
        public int CERTIFICATION_NAME_PRODUCT { get; set; }
        public bool CERTIFICATION_NAME_ACTIVE { get; set; }
    }
}
