//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATION_OTHERS
    {
        public int CERTIFICATION_OTHERS_ID { get; set; }
        public string CERTIFICATION_OTHERS_NAME { get; set; }
        public Nullable<int> CERTIFICATION_OTHERS_PRODUCTLINE { get; set; }
        public Nullable<int> CERTIFICATION_OTHERS_PRODUCT { get; set; }
        public string CERTIFICATION_OTHERS_URL { get; set; }
        public int CERTIFICATION_OTHERS_PAGE { get; set; }
        public string CERTIFICATION_OTHERS_TYPE { get; set; }
        public int CERTIFICATION_OTHERS_SIZE { get; set; }
        public string CERTIFICATION_OTHERS_LINK_NAME { get; set; }
        public string CERTIFICATION_OTHERS_ICON { get; set; }
        public int CERTIFICATION_OTHERS_ORDER { get; set; }
        public bool CERTIFICATION_OTHERS_ACTIVE { get; set; }
    }
}
