//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATION_PRODUCTLINE
    {
        public int CERTIFICATION_PRODUCTLINE_ID { get; set; }
        public string CERTIFICATION_PRODUCTLINE1 { get; set; }
        public int CERTIFICATION_PRODUCTLINE_ORDER { get; set; }
        public bool CERTIFICATION_PRODUCTLINE_ACTIVE { get; set; }
    }
}
