//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPUTERSUPPORT
    {
        public int CS_ID { get; set; }
        public int EMP_ID { get; set; }
        public int DEP_ID { get; set; }
        public System.DateTime CS_DATE { get; set; }
        public string CS_PROBLEM { get; set; }
        public int PRIORITY_ID { get; set; }
        public int STAT_ID { get; set; }
        public string CS_SOLUTION { get; set; }
        public Nullable<System.DateTime> CS_DATEMODIFIED { get; set; }
        public string CS_MODIFIEDBY { get; set; }
        public bool CS_PROCESS { get; set; }
        public Nullable<int> PC_ID { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PRIORITY PRIORITY { get; set; }
        public virtual STATUSCPSUP STATUSCPSUP { get; set; }
    }
}
