//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.DISTRIBUTOR_GROUP_PRICE = new HashSet<DISTRIBUTOR_GROUP_PRICE>();
        }
    
        public int CO_ID { get; set; }
        public string CO_NAME { get; set; }
    
        public virtual ICollection<DISTRIBUTOR_GROUP_PRICE> DISTRIBUTOR_GROUP_PRICE { get; set; }
    }
}
