//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPUTERSUPP
    {
        public int CS_ID { get; set; }
        public System.DateTime CS_DATE { get; set; }
        public string CS_EMPNAME { get; set; }
        public string CS_EMPEXT { get; set; }
        public string CS_DEPNAME { get; set; }
        public string CS_MANAGER { get; set; }
        public string CS_PROBLEM { get; set; }
        public string CS_SOLUTION { get; set; }
        public Nullable<short> CS_PRIORITY { get; set; }
        public bool CS_STATUS { get; set; }
        public Nullable<System.DateTime> CS_DATEMODIFIED { get; set; }
        public string CS_MODIFIEDBY { get; set; }
    }
}
