//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.SUPPLIERs = new HashSet<SUPPLIER>();
            this.DISTRIBUTORs = new HashSet<DISTRIBUTOR>();
            this.WBDISUSERS = new HashSet<WBDISUSER>();
        }
    
        public int CTRY_ID { get; set; }
        public string CTRY_NO { get; set; }
        public string CTRY_DES { get; set; }
        public string CTRY_CONTINENT { get; set; }
        public string CTRY_DES_FR { get; set; }
        public string CTRY_CONTINENT_FR { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<SUPPLIER> SUPPLIERs { get; set; }
        public virtual ICollection<DISTRIBUTOR> DISTRIBUTORs { get; set; }
        public virtual ICollection<WBDISUSER> WBDISUSERS { get; set; }
    }
}
