//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRT_PRODUCT_GROUP
    {
        public int PRODUCT_GROUP_ID { get; set; }
        public Nullable<int> PRODUCT_GROUP_PRODUCT_LINE { get; set; }
        public string PRODUCT_GROUP_NAME { get; set; }
        public Nullable<int> PRODUCT_GROUP_ORDER { get; set; }
        public bool ACTIVE { get; set; }
    }
}
