//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRT_VERSION_NOTE
    {
        public int VERSION_NOTE_ID { get; set; }
        public int PRODUCT_LINE_ID { get; set; }
        public string VERSION_NOTE_TEXT { get; set; }
        public string VERSION_NOTE_COLOR { get; set; }
        public int VERSION_NOTE_ORDER { get; set; }
        public bool ACTIVE { get; set; }
    }
}
