//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRT_COMPATIBILITY
    {
        public int PRODUCT_ID { get; set; }
        public Nullable<int> CONTROL_VERSION_ID { get; set; }
        public bool COMPATIBILITY { get; set; }
        public Nullable<int> VERSION_NOTE { get; set; }
    }
}
