//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRT_PRODUCT_LINE
    {
        public int PRODUCT_ID { get; set; }
        public int CHART_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<int> PRODUCT_ORDER { get; set; }
        public bool ACTIVE { get; set; }
    }
}
