//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRT_CONTROL_PANEL
    {
        public int CONTROL_PANEL_ID { get; set; }
        public Nullable<int> CONTROL_PANEL_PRODUCT_LINE { get; set; }
        public string CONTROL_PANEL_NAME { get; set; }
        public Nullable<int> CONTROL_PANEL_ORDER { get; set; }
        public Nullable<bool> DISCONTINUE { get; set; }
        public bool ACTIVE { get; set; }
    }
}
