//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALER
    {
        public int DI_ID { get; set; }
        public int DEA_ID { get; set; }
        public string DEA_USR { get; set; }
        public string DEA_PASSWORD { get; set; }
        public string DEA_DISTNO { get; set; }
        public string DEA_FIRSTNAME { get; set; }
        public string DEA_LASTNAME { get; set; }
        public string DEA_COMPANY { get; set; }
        public string DEA_OCCUP { get; set; }
        public string DEA_AD1 { get; set; }
        public string DEA_AD2 { get; set; }
        public string DEA_AD3 { get; set; }
        public string DEA_ZC { get; set; }
        public string DEA_CTRY { get; set; }
        public string DEA_PHONE { get; set; }
        public string DEA_FAX { get; set; }
        public System.DateTime DEA_OPENED { get; set; }
        public Nullable<System.DateTime> DEA_EXPIRED { get; set; }
        public bool DEA_ACTIVITY { get; set; }
        public Nullable<bool> DEA_IS_DELETED { get; set; }
        public Nullable<int> BR_ID { get; set; }
        public string DEA_SHIPVIA { get; set; }
        public string DEA_EMAIL { get; set; }
        public bool DEA_MAILLIST { get; set; }
        public string DEA_LANGUAGE { get; set; }
        public bool ASK_REGISTER { get; set; }
        public string ASK_MSGREG { get; set; }
        public System.DateTime DEA_LASTACTIVITY { get; set; }
        public int DEA_COMENBR { get; set; }
        public bool DEA_ISTREATED { get; set; }
        public string DEA_HTTP_HOST { get; set; }
        public string DEA_HTTP_USER_AGENT { get; set; }
        public bool DEA_CANORDER { get; set; }
        public bool DEA_IS_CONFIRMED { get; set; }
        public string DEA_SESSIONID { get; set; }
    
        public virtual DISTRIBUTOR DISTRIBUTOR { get; set; }
    }
}
