//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.COMPUTERSUPPORTs = new HashSet<COMPUTERSUPPORT>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.TS_MASTERPRJ = new HashSet<TS_MASTERPRJ>();
            this.TS_MASTERPRJ1 = new HashSet<TS_MASTERPRJ>();
        }
    
        public int DEP_ID { get; set; }
        public Nullable<int> NS_DEP_ID { get; set; }
        public Nullable<bool> DEP_ACTIVITY { get; set; }
        public string DEP_NAME { get; set; }
        public Nullable<int> RESP_EMP_ID { get; set; }
        public Nullable<int> DEP_ORDER { get; set; }
        public Nullable<int> DEP_GRP { get; set; }
        public string DEP_DES { get; set; }
        public Nullable<int> DEP_CODE_EXT { get; set; }
        public Nullable<int> DEP_NS_ID { get; set; }
    
        public virtual ICollection<COMPUTERSUPPORT> COMPUTERSUPPORTs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<TS_MASTERPRJ> TS_MASTERPRJ { get; set; }
        public virtual ICollection<TS_MASTERPRJ> TS_MASTERPRJ1 { get; set; }
    }
}
