//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT_SECOURISTE
    {
        public int DEPARTMENT_ID { get; set; }
        public string DEPARTMENT_NAME_FR { get; set; }
        public string DEPARTMENT_NAME_EN { get; set; }
    }
}
