//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUTOR
    {
        public DISTRIBUTOR()
        {
            this.DEALERs = new HashSet<DEALER>();
            this.DISTRIBSHIPTOes = new HashSet<DISTRIBSHIPTO>();
            this.WBDISUSERS = new HashSet<WBDISUSER>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public int DI_ID { get; set; }
        public bool DI_ACTIVITY { get; set; }
        public string INV_NO { get; set; }
        public Nullable<int> GRP_ID { get; set; }
        public Nullable<int> PRI_ID { get; set; }
        public Nullable<int> DI_MASTERID { get; set; }
        public bool DI_HASSUBS { get; set; }
        public string DI_NAME { get; set; }
        public string DI_AD1 { get; set; }
        public string DI_AD2 { get; set; }
        public string DI_AD3 { get; set; }
        public string DI_ZC { get; set; }
        public string DI_CTRY { get; set; }
        public string DI_PHONE { get; set; }
        public string DI_FAX { get; set; }
        public string DI_ATT { get; set; }
        public string DI_CUR { get; set; }
        public string DI_EMAIL { get; set; }
        public string DI_EMAILCC { get; set; }
        public string DI_EMAILTO_OODEALER { get; set; }
        public string DI_EMAILTO_REQUEST { get; set; }
        public string DI_EMAILBCC_REQUEST { get; set; }
        public bool DI_MAILLIST { get; set; }
        public System.DateTime DI_OPENED { get; set; }
        public string DI_WEBSITE { get; set; }
        public string DI_LOGO { get; set; }
        public string PARA_EMAILTO { get; set; }
        public string PARA_EMAILCC { get; set; }
        public bool DI_GSTCHARGE { get; set; }
        public bool DI_PSTCHARGE { get; set; }
        public Nullable<double> DI_DISC { get; set; }
        public string DI_METPAID { get; set; }
        public string DI_SHIPVIA { get; set; }
        public Nullable<bool> DI_POSITION_ORDER { get; set; }
        public bool DI_PARAORDER { get; set; }
        public Nullable<bool> DI_WEB_PARADOX { get; set; }
        public Nullable<bool> DI_WEB_POSITION { get; set; }
        public Nullable<bool> DI_GILBOA_ORDER { get; set; }
        public System.DateTime PRI_LASTUPD { get; set; }
        public string PRI_LASTUSR { get; set; }
        public bool DI_MARKETING_FUND { get; set; }
        public int DI_PRI_COL { get; set; }
        public string DI_LASTUSRACT { get; set; }
        public System.DateTime DI_LASTACT { get; set; }
        public bool PACK_SEPRATE { get; set; }
        public int DISPLAY_PRIORITY { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<DEALER> DEALERs { get; set; }
        public virtual ICollection<DISTRIBSHIPTO> DISTRIBSHIPTOes { get; set; }
        public virtual ICollection<WBDISUSER> WBDISUSERS { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
