//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBSHIPTO
    {
        public int DI_ID { get; set; }
        public int SHI_ID { get; set; }
        public string SHI_NAME { get; set; }
        public string SHI_AD1 { get; set; }
        public string SHI_AD2 { get; set; }
        public string SHI_AD3 { get; set; }
        public Nullable<int> TAXES_ID { get; set; }
        public string SHI_ZC { get; set; }
        public string SHI_CTRY { get; set; }
        public string SHI_PHONE { get; set; }
        public string SHI_FAX { get; set; }
        public string SHI_ATT { get; set; }
        public string SHI_SHIPVIA { get; set; }
        public Nullable<int> SHI_TYPE { get; set; }
        public string SHI_CUR { get; set; }
        public Nullable<bool> SHI_GSTCHARGE { get; set; }
        public Nullable<bool> SHI_PSTCHARGE { get; set; }
        public Nullable<bool> SHI_IS_DELETED { get; set; }
    
        public virtual DISTRIBUTOR DISTRIBUTOR { get; set; }
    }
}
