//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBGROUP
    {
        public int GRP_ID { get; set; }
        public bool GRP_ACTIVITY { get; set; }
        public string GRP_NAME { get; set; }
        public string GRP_DESCRIP { get; set; }
        public string GRP_DESCRIPTION { get; set; }
        public int GRP_COLUMN { get; set; }
        public string GRP_USER { get; set; }
        public string GRP_PASSWORD { get; set; }
    }
}
