//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.COMPUTERSUPPORTs = new HashSet<COMPUTERSUPPORT>();
            this.FIRETEAMs = new HashSet<FIRETEAM>();
            this.FIRETEAMs1 = new HashSet<FIRETEAM>();
            this.INFOMANAGs = new HashSet<INFOMANAG>();
            this.TimeSheetProjects = new HashSet<TimeSheetProject>();
            this.TimeSheetUserProjectLinks = new HashSet<TimeSheetUserProjectLink>();
            this.TS_PUNCH = new HashSet<TS_PUNCH>();
            this.DISTRIBUTORs = new HashSet<DISTRIBUTOR>();
            this.GRPEMAILs = new HashSet<GRPEMAIL>();
        }
    
        public int EMP_ID { get; set; }
        public Nullable<int> PAYROLL_ID { get; set; }
        public Nullable<int> DEP_ID { get; set; }
        public Nullable<int> GRP_ID { get; set; }
        public bool EMP_ACTIVITY { get; set; }
        public string EMP_USR { get; set; }
        public string EMP_PASSWORD { get; set; }
        public string EMP_LASTNAME { get; set; }
        public string EMP_FIRSTNAME { get; set; }
        public string EMP_IMAGE { get; set; }
        public string EMP_AD1 { get; set; }
        public string EMP_AD2 { get; set; }
        public string EMP_AD3 { get; set; }
        public string EMP_ZC { get; set; }
        public string EMP_CTRY { get; set; }
        public string EMP_PHONE { get; set; }
        public string EMP_WORK_PHONE { get; set; }
        public string EMP_EXTENSION { get; set; }
        public string EMP_CELL_PHONE { get; set; }
        public string EMP_FAX { get; set; }
        public string EMP_EMAIL { get; set; }
        public string EMP_OCCUPATION { get; set; }
        public int EMP_BRANCH { get; set; }
        public System.DateTime EMP_OPENDATE { get; set; }
        public Nullable<System.DateTime> EMP_EXPIRED { get; set; }
        public Nullable<System.DateTime> EMP_TRANSFERDATE { get; set; }
        public System.DateTime EMP_HIREDATE { get; set; }
        public Nullable<System.DateTime> EMP_BIRTHDAY { get; set; }
        public int EMP_GENDER { get; set; }
        public int EMP_STATUS { get; set; }
        public int EMP_MARITAL_STATUS { get; set; }
        public int TGR_ID { get; set; }
        public Nullable<bool> ACCESSDEALER { get; set; }
        public Nullable<bool> ACCESSDISTRIB { get; set; }
        public Nullable<bool> ACCESSDISORDER { get; set; }
        public Nullable<int> EMP_ACCESS { get; set; }
        public Nullable<System.DateTime> PICTUREDATE { get; set; }
        public string EVAL_NOTE { get; set; }
        public long EMP_WEBSITE_ACCESS { get; set; }
        public long EMP_OLO_ACCESS { get; set; }
        public int EMP_TYPE { get; set; }
        public Nullable<System.DateTime> NEXT_EVALUATION_DATE { get; set; }
        public bool SHOW_PICTURE { get; set; }
        public int BANK { get; set; }
        public Nullable<int> USR_ID { get; set; }
    
        public virtual ICollection<COMPUTERSUPPORT> COMPUTERSUPPORTs { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<FIRETEAM> FIRETEAMs { get; set; }
        public virtual ICollection<FIRETEAM> FIRETEAMs1 { get; set; }
        public virtual FIRSTAIDWORKER FIRSTAIDWORKER { get; set; }
        public virtual ICollection<INFOMANAG> INFOMANAGs { get; set; }
        public virtual ICollection<TimeSheetProject> TimeSheetProjects { get; set; }
        public virtual ICollection<TimeSheetUserProjectLink> TimeSheetUserProjectLinks { get; set; }
        public virtual ICollection<TS_PUNCH> TS_PUNCH { get; set; }
        public virtual ICollection<DISTRIBUTOR> DISTRIBUTORs { get; set; }
        public virtual ICollection<GRPEMAIL> GRPEMAILs { get; set; }
    }
}
