//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_ACCESS
    {
        public int EMP_ID { get; set; }
        public int ACC_ID { get; set; }
    
        public virtual ACCESS ACCESS { get; set; }
    }
}
