//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXACT_DEPARTMENT
    {
        public int DEP_ID { get; set; }
        public Nullable<bool> DEP_ACTIVITY { get; set; }
        public string DEP_NAME { get; set; }
        public Nullable<int> RESP_EMP_ID { get; set; }
        public Nullable<int> DEP_ORDER { get; set; }
        public Nullable<int> DEP_GRP { get; set; }
        public string DEP_DES { get; set; }
        public Nullable<int> DEP_CODE_EXT { get; set; }
    }
}
