//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_CATEGORY
    {
        public int CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string CATEGORY_ALIAS { get; set; }
        public string CATEGORY_DESCRIPTION { get; set; }
        public Nullable<bool> CATEGORY_ACTIVITY { get; set; }
        public Nullable<int> CATEGORY_ORDER { get; set; }
        public string CATEGORY_PDF { get; set; }
        public string CATEGORY_PDF_DETAIL { get; set; }
    }
}
