//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_SUBCATEGORY
    {
        public int SUBCATEGORY_ID { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string SUBCATEGORY_NAME { get; set; }
        public string SUBCATEGORY_ALIAS { get; set; }
        public Nullable<bool> SUBCATEGORY_ACTIVITY { get; set; }
        public Nullable<int> SUBCATEGORY_ORDER { get; set; }
    }
}
