//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_FAQ
    {
        public int FAQ_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public string FAQ_CATEGORY { get; set; }
        public string FAQ_QUESTION { get; set; }
        public string FAQ_ANSWER { get; set; }
        public string FAQ_FILE { get; set; }
        public Nullable<System.DateTime> FAQ_DATE { get; set; }
        public Nullable<bool> FAQ_ACTIVITY { get; set; }
    }
}
