//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINDDISTRIBUTOR_SUBDISTRIBUTOR
    {
        public int FINDSUBDIS_ID { get; set; }
        public Nullable<int> DI_ID { get; set; }
        public string CTRY_NO { get; set; }
        public string FINDSUBDIS_COMPANY { get; set; }
        public string FINDSUBDIS_ADDRESS { get; set; }
        public string FINDSUBDIS_ATT { get; set; }
        public string FINDSUBDIS_PHONE { get; set; }
        public string FINDSUBDIS_FAX { get; set; }
        public string FINDSUBDIS_EMAIL { get; set; }
        public string FINDSUBDIS_WEBSITE { get; set; }
        public Nullable<int> FINDSUBDIS_ORDER { get; set; }
        public bool IS_DELETED { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
