//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMWARE_UPDATE
    {
        public int FIRMWARE_UPDATE_ID { get; set; }
        public Nullable<int> FIRMWARE_UPDATE_DISTRIBUTOR { get; set; }
        public int FIRMWARE_UPDATE_PRODUCT { get; set; }
        public string FIRMWARE_UPDATE_VERSION { get; set; }
        public System.DateTime FIRMWARE_UPDATE_DATE { get; set; }
        public bool FIRMWARE_UPDATE_ACTIVE { get; set; }
    }
}
