//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMWARE_UPDATE_HISTORY
    {
        public int FIRMWARE_UPDATE_HISTORY_ID { get; set; }
        public Nullable<int> FIRMWARE_UPDATE_HISTORY_GROUP { get; set; }
        public Nullable<int> FIRMWARE_UPDATE_HISTORY_DISTRIBUTOR { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_VERSION { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_DATE { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_PI { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_PI_LINK { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_FU { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_FU_LINK { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_ALL_MANUALS { get; set; }
        public Nullable<int> FIRMWARE_UPDATE_HISTORY_ORDER { get; set; }
        public string FIRMWARE_UPDATE_HISTORY_MESSAGE { get; set; }
        public Nullable<bool> FIRMWARE_UPDATE_HISTORY_BETA { get; set; }
        public Nullable<bool> FIRMWARE_UPDATE_HISTORY_ACTIVE { get; set; }
    }
}
