//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMWARE_UPDATE_PRODUCT
    {
        public int FIRMWARE_UPDATE_PRODUCT_ID { get; set; }
        public Nullable<int> PT_PRODUCT_ID { get; set; }
        public int FIRMWARE_UPDATE_PRODUCT_LINE { get; set; }
        public string FIRMWARE_UPDATE_PRODUCT_NAME { get; set; }
        public string FIRMWARE_UPDATE_PRODUCT_URL { get; set; }
        public bool FIRMWARE_UPDATE_PRODUCT_ACTIVE { get; set; }
    }
}
