//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMWARE_UPDATE_PRODUCTGROUP
    {
        public int FIRMWARE_UPDATE_PRODUCTGROUP_ID { get; set; }
        public string FIRMWARE_UPDATE_PRODUCTGROUP_NAME { get; set; }
        public string FIRMWARE_UPDATE_PRODUCTGROUP_LINK { get; set; }
        public string FIRMWARE_UPDATE_PRODUCTGROUP_LOGO { get; set; }
        public Nullable<bool> FIRMWARE_UPDATE_PRODUCTGROUP_ACTIVE { get; set; }
    }
}
