//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMWARE_UPDATE_FIRMWARE
    {
        public int FIRMWARE_UPDATE_FIRMWARE_ID { get; set; }
        public Nullable<int> FIRMWARE_UPDATE_FIRMWARE_HISTORY_ID { get; set; }
        public string FIRMWARE_UPDATE_FIRMWARE_NAME { get; set; }
        public string FIRMWARE_UPDATE_FIRMWARE_LINK { get; set; }
        public Nullable<int> FIRMWARE_UPDATE_FIRMWARE_ORDER { get; set; }
        public Nullable<bool> FIRMWARE_UPDATE_FIRMWARE_ACTIVE { get; set; }
    }
}
