//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_CATEGORY
    {
        public int FCAT_ID { get; set; }
        public string FCAT_NAME { get; set; }
        public string FCAT_DESCRIPTION { get; set; }
        public Nullable<int> FCAT_ORDER { get; set; }
        public Nullable<bool> FCAT_ACTIVITY { get; set; }
    }
}
