//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_MESSAGE
    {
        public int FMESSAGE_ID { get; set; }
        public Nullable<int> FCAT_ID { get; set; }
        public string FMESSAGE_SUBJECT { get; set; }
        public string FMESSAGE_MESSAGE { get; set; }
        public Nullable<bool> FMESSAGE_ACTIVITY { get; set; }
        public string FMESSAGE_POSTBY_USR { get; set; }
        public Nullable<System.DateTime> FMESSAGE_DATE { get; set; }
        public Nullable<int> EMP_ID__TMP { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string FMESSAGE_FILE { get; set; }
    }
}
