//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_MESSAGE_VIEW
    {
        public int ID { get; set; }
        public Nullable<int> FMESSAGE_ID { get; set; }
        public string FMV_USER { get; set; }
        public Nullable<System.DateTime> FMV_DATE { get; set; }
    }
}
