//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORUM_REPLY
    {
        public int FREPLY_ID { get; set; }
        public Nullable<int> FMESSAGE_ID { get; set; }
        public string FREPLY_SUBJECT { get; set; }
        public string FREPLY_MESSAGE { get; set; }
        public Nullable<bool> FREPLY_ACTIVITY { get; set; }
        public string FREPLY_NIVEAU { get; set; }
        public string FREPLY_REPLYBY_USR { get; set; }
        public Nullable<System.DateTime> FREPLY_DATE { get; set; }
        public Nullable<int> EMP_ID__TMP { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string FREPLY_FILE { get; set; }
    }
}
