//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRPEMAIL
    {
        public GRPEMAIL()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public int GRE_ID { get; set; }
        public Nullable<int> GRE_ORDER { get; set; }
        public string GRE_NAME { get; set; }
        public string GRE_DESC { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
