//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOUTILITy
    {
        public int IUT_ID { get; set; }
        public string IUT_TITLE { get; set; }
        public string IUT_DESCRIPTION { get; set; }
        public System.DateTime IUT_DATE { get; set; }
        public bool IUT_MANAGER { get; set; }
        public bool IUT_ALL { get; set; }
        public int EMP_ID { get; set; }
    }
}
