//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOMANAG
    {
        public int INFO_ID { get; set; }
        public int EMP_ID { get; set; }
        public System.DateTime INFO_DATE { get; set; }
        public Nullable<System.DateTime> INFO_DTIMEIN { get; set; }
        public Nullable<System.DateTime> INFO_DTIMEOUT { get; set; }
        public string INFO_NOTE { get; set; }
        public bool INFO_OUT { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
