//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_SN
    {
        public string SN_ID { get; set; }
        public System.TimeSpan START { get; set; }
        public Nullable<System.TimeSpan> END_TIME { get; set; }
        public Nullable<int> DIFF { get; set; }
    }
}
