//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_ON_PARADOX
    {
        public int LOGIN_ID { get; set; }
        public string LOGIN_USR { get; set; }
        public Nullable<System.DateTime> LOGIN_DATE { get; set; }
        public Nullable<int> LOGIN_GROUP { get; set; }
        public string LOGIN_SECTION { get; set; }
        public string LOGIN_IP { get; set; }
        public string LOGIN_HTTP_USER_AGENT { get; set; }
    }
}
