//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBParadoxEntities : DbContext
    {
        public DBParadoxEntities()
            : base("name=DBParadoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_PARA_VISITS> C_PARA_VISITS { get; set; }
        public DbSet<ACCESS> ACCESSes { get; set; }
        public DbSet<CAREER> CAREERS { get; set; }
        public DbSet<CAREERS_MIAMI> CAREERS_MIAMI { get; set; }
        public DbSet<CERTIFICATION_OTHERS> CERTIFICATION_OTHERS { get; set; }
        public DbSet<CITy> CITIES { get; set; }
        public DbSet<COMPANY> COMPANies { get; set; }
        public DbSet<COMPUTERSUPP> COMPUTERSUPPs { get; set; }
        public DbSet<COMPUTERSUPPORT> COMPUTERSUPPORTs { get; set; }
        public DbSet<COUNTRY> COUNTRies { get; set; }
        public DbSet<CURRENCY> CURRENCies { get; set; }
        public DbSet<DEALER> DEALERs { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public DbSet<DEPARTMENT_SECOURISTE> DEPARTMENT_SECOURISTE { get; set; }
        public DbSet<DISGRPEMAIL> DISGRPEMAILs { get; set; }
        public DbSet<DISTRIBGROUP> DISTRIBGROUPs { get; set; }
        public DbSet<DISTRIBGROUP_PRICE> DISTRIBGROUP_PRICE { get; set; }
        public DbSet<DISTRIBSHIPTO> DISTRIBSHIPTOes { get; set; }
        public DbSet<DISTRIBUTOR> DISTRIBUTORs { get; set; }
        public DbSet<DISTRIBUTOR_GROUP> DISTRIBUTOR_GROUP { get; set; }
        public DbSet<DISTRIBUTOR_GROUP_PRICE> DISTRIBUTOR_GROUP_PRICE { get; set; }
        public DbSet<dtproperty> dtproperties { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public DbSet<EMPLOYEE_ACCESS> EMPLOYEE_ACCESS { get; set; }
        public DbSet<EMPLOYEE_GROUP> EMPLOYEE_GROUP { get; set; }
        public DbSet<FAQ_CATEGORY> FAQ_CATEGORY { get; set; }
        public DbSet<FAQ_FAQ> FAQ_FAQ { get; set; }
        public DbSet<FAQ_SUBCATEGORY> FAQ_SUBCATEGORY { get; set; }
        public DbSet<FINDDISTRIBUTOR_SUBDISTRIBUTOR> FINDDISTRIBUTOR_SUBDISTRIBUTOR { get; set; }
        public DbSet<FIRETEAM> FIRETEAMs { get; set; }
        public DbSet<FIRMWARE_UPDATE> FIRMWARE_UPDATE { get; set; }
        public DbSet<FIRMWARE_UPDATE_FIRMWARE> FIRMWARE_UPDATE_FIRMWARE { get; set; }
        public DbSet<FIRMWARE_UPDATE_HISTORY> FIRMWARE_UPDATE_HISTORY { get; set; }
        public DbSet<FIRMWARE_UPDATE_IMPROVEMENT> FIRMWARE_UPDATE_IMPROVEMENT { get; set; }
        public DbSet<FIRMWARE_UPDATE_NEW> FIRMWARE_UPDATE_NEW { get; set; }
        public DbSet<FIRMWARE_UPDATE_NEWS> FIRMWARE_UPDATE_NEWS { get; set; }
        public DbSet<FIRMWARE_UPDATE_PRODUCT> FIRMWARE_UPDATE_PRODUCT { get; set; }
        public DbSet<FIRMWARE_UPDATE_PRODUCTGROUP> FIRMWARE_UPDATE_PRODUCTGROUP { get; set; }
        public DbSet<FORUM_CATEGORY> FORUM_CATEGORY { get; set; }
        public DbSet<FORUM_MESSAGE> FORUM_MESSAGE { get; set; }
        public DbSet<FORUM_MESSAGE_VIEW> FORUM_MESSAGE_VIEW { get; set; }
        public DbSet<FORUM_REPLY> FORUM_REPLY { get; set; }
        public DbSet<GRPEMAIL> GRPEMAILs { get; set; }
        public DbSet<INFOMANAG> INFOMANAGs { get; set; }
        public DbSet<INFOUTILITy> INFOUTILITIES { get; set; }
        public DbSet<LOG_SN> LOG_SN { get; set; }
        public DbSet<LOGIN_ON_PARADOX> LOGIN_ON_PARADOX { get; set; }
        public DbSet<NE_CERTIFICATE_LOG> NE_CERTIFICATE_LOG { get; set; }
        public DbSet<NE_REGISTRATION> NE_REGISTRATION { get; set; }
        public DbSet<NE_REGISTRATION_HISTORY> NE_REGISTRATION_HISTORY { get; set; }
        public DbSet<NE_SERIAL> NE_SERIAL { get; set; }
        public DbSet<NE_SERIAL_FOR_PRINTER_ACCESS> NE_SERIAL_FOR_PRINTER_ACCESS { get; set; }
        public DbSet<NE_SERIAL_FOR_PRINTER_SECURITY> NE_SERIAL_FOR_PRINTER_SECURITY { get; set; }
        public DbSet<NE_VERSION> NE_VERSION { get; set; }
        public DbSet<OTHEREXT> OTHEREXTs { get; set; }
        public DbSet<PCINVENTORY> PCINVENTORies { get; set; }
        public DbSet<Pedometer_groups> Pedometer_groups { get; set; }
        public DbSet<pedometer_user_data> pedometer_user_data { get; set; }
        public DbSet<pedometer_users> pedometer_users { get; set; }
        public DbSet<Pedometer> Pedometers { get; set; }
        public DbSet<PRIORITY> PRIORITies { get; set; }
        public DbSet<PRODUCT> PRODUCTs { get; set; }
        public DbSet<PROTOCOL_PRODUCT> PROTOCOL_PRODUCT { get; set; }
        public DbSet<PROTOCOL_PRODUCT_FILE> PROTOCOL_PRODUCT_FILE { get; set; }
        public DbSet<PROTOCOL_REQUEST> PROTOCOL_REQUEST { get; set; }
        public DbSet<PROVSTATE> PROVSTATEs { get; set; }
        public DbSet<PT_CENTER> PT_CENTER { get; set; }
        public DbSet<PT_PRODUCT> PT_PRODUCT { get; set; }
        public DbSet<PT_PRODUCT_GROUP> PT_PRODUCT_GROUP { get; set; }
        public DbSet<PT_PRODUCT_LINE> PT_PRODUCT_LINE { get; set; }
        public DbSet<QC_NOTIFICATION_PRODUCTION_PRODUCT> QC_NOTIFICATION_PRODUCTION_PRODUCT { get; set; }
        public DbSet<RL_LOG_ACCEPT> RL_LOG_ACCEPT { get; set; }
        public DbSet<RL_LOG_CONFIRMED> RL_LOG_CONFIRMED { get; set; }
        public DbSet<RL_LOG_DECLINE> RL_LOG_DECLINE { get; set; }
        public DbSet<RL_LOG_DELETE_NOT_CONFIRMED> RL_LOG_DELETE_NOT_CONFIRMED { get; set; }
        public DbSet<RL_LOG_REQUEST> RL_LOG_REQUEST { get; set; }
        public DbSet<SERIALNUMBER_PRODUCTLIST> SERIALNUMBER_PRODUCTLIST { get; set; }
        public DbSet<SHIPPING_TYPE> SHIPPING_TYPE { get; set; }
        public DbSet<SN> SNs { get; set; }
        public DbSet<SN_QUEUE> SN_QUEUE { get; set; }
        public DbSet<SOFTWARELIST> SOFTWARELISTs { get; set; }
        public DbSet<STATUSBUG> STATUSBUGs { get; set; }
        public DbSet<STATUSCPSUP> STATUSCPSUPs { get; set; }
        public DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public DbSet<SURVEY_1> SURVEY_1 { get; set; }
        public DbSet<SURVEY_DISTRIBUTOR> SURVEY_DISTRIBUTOR { get; set; }
        public DbSet<SURVEY_DISTRIBUTOR_EMP> SURVEY_DISTRIBUTOR_EMP { get; set; }
        public DbSet<SURVEY_DISTRIBUTOR_QUESTION> SURVEY_DISTRIBUTOR_QUESTION { get; set; }
        public DbSet<SURVEY_DISTRIBUTOR_USER> SURVEY_DISTRIBUTOR_USER { get; set; }
        public DbSet<SURVEY_MAILINGLIST> SURVEY_MAILINGLIST { get; set; }
        public DbSet<SURVEY_MAILINGLISTSUBJECT> SURVEY_MAILINGLISTSUBJECT { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TAX> TAXES { get; set; }
        public DbSet<TimeSheetFilterGroup> TimeSheetFilterGroups { get; set; }
        public DbSet<TimeSheetProject> TimeSheetProjects { get; set; }
        public DbSet<TimeSheetTracking> TimeSheetTrackings { get; set; }
        public DbSet<TimeSheetUserProjectLink> TimeSheetUserProjectLinks { get; set; }
        public DbSet<TS_EXACT_SUBMIT> TS_EXACT_SUBMIT { get; set; }
        public DbSet<TS_EXPENSES> TS_EXPENSES { get; set; }
        public DbSet<TS_MASTERPRJ> TS_MASTERPRJ { get; set; }
        public DbSet<TS_PARAMETER> TS_PARAMETER { get; set; }
        public DbSet<TS_PAYROLL> TS_PAYROLL { get; set; }
        public DbSet<TS_PERIOD> TS_PERIOD { get; set; }
        public DbSet<TS_PRDLIST_PARAMETER> TS_PRDLIST_PARAMETER { get; set; }
        public DbSet<TS_PRJ_EMP> TS_PRJ_EMP { get; set; }
        public DbSet<TS_PRODUCT> TS_PRODUCT { get; set; }
        public DbSet<TS_PRODUCTPROJECT> TS_PRODUCTPROJECT { get; set; }
        public DbSet<TS_PUNCH> TS_PUNCH { get; set; }
        public DbSet<TS_REASON> TS_REASON { get; set; }
        public DbSet<TS_STATUS> TS_STATUS { get; set; }
        public DbSet<TS_SUBMIT> TS_SUBMIT { get; set; }
        public DbSet<TS_TASK> TS_TASK { get; set; }
        public DbSet<TS_TASKS> TS_TASKS { get; set; }
        public DbSet<TS_TIMEGRP> TS_TIMEGRP { get; set; }
        public DbSet<TS_TIMESHEET> TS_TIMESHEET { get; set; }
        public DbSet<TS_TYPE> TS_TYPE { get; set; }
        public DbSet<USER_IMPERIAL> USER_IMPERIAL { get; set; }
        public DbSet<USR_GROUP_DISTRIBUTOR_PRICING> USR_GROUP_DISTRIBUTOR_PRICING { get; set; }
        public DbSet<VIP_CONFERENCE_2003> VIP_CONFERENCE_2003 { get; set; }
        public DbSet<VIP_CONFERENCE_2003_FRIEND> VIP_CONFERENCE_2003_FRIEND { get; set; }
        public DbSet<VIP_CONFERENCE_2003_USER> VIP_CONFERENCE_2003_USER { get; set; }
        public DbSet<WBDISUSER> WBDISUSERS { get; set; }
        public DbSet<WBTECHSUPP> WBTECHSUPPs { get; set; }
        public DbSet<CERTIFICATION_CE> CERTIFICATION_CE { get; set; }
        public DbSet<CERTIFICATION_NAME> CERTIFICATION_NAME { get; set; }
        public DbSet<CERTIFICATION_PRODUCT> CERTIFICATION_PRODUCT { get; set; }
        public DbSet<CERTIFICATION_PRODUCTLINE> CERTIFICATION_PRODUCTLINE { get; set; }
        public DbSet<CRT_COMPATIBILITY> CRT_COMPATIBILITY { get; set; }
        public DbSet<CRT_CONTROL_PANEL> CRT_CONTROL_PANEL { get; set; }
        public DbSet<CRT_CONTROL_PANEL_VERSION> CRT_CONTROL_PANEL_VERSION { get; set; }
        public DbSet<CRT_PRODUCT> CRT_PRODUCT { get; set; }
        public DbSet<CRT_PRODUCT_GROUP> CRT_PRODUCT_GROUP { get; set; }
        public DbSet<CRT_PRODUCT_LINE> CRT_PRODUCT_LINE { get; set; }
        public DbSet<CRT_VERSION_NOTE> CRT_VERSION_NOTE { get; set; }
        public DbSet<DELETED_NE_REGISTRATION> DELETED_NE_REGISTRATION { get; set; }
        public DbSet<DEPARTMENT_TIMESHEET_MINUTES> DEPARTMENT_TIMESHEET_MINUTES { get; set; }
        public DbSet<EXACT_DEPARTMENT> EXACT_DEPARTMENT { get; set; }
        public DbSet<FIRMWARE_UPDATE_MULTIPLE_FIRMWARE> FIRMWARE_UPDATE_MULTIPLE_FIRMWARE { get; set; }
        public DbSet<FIRSTAIDWORKER> FIRSTAIDWORKERS { get; set; }
        public DbSet<IntranetHoliday> IntranetHolidays { get; set; }
        public DbSet<NE_REGISTRATION_DEMO> NE_REGISTRATION_DEMO { get; set; }
        public DbSet<NE_REGISTRATION_UPGRADE> NE_REGISTRATION_UPGRADE { get; set; }
        public DbSet<PICTURE> PICTUREs { get; set; }
        public DbSet<PICTUREGROUP> PICTUREGROUPs { get; set; }
        public DbSet<PICTUREGROUPPRODUCT> PICTUREGROUPPRODUCTs { get; set; }
        public DbSet<PICTUREPRODUCT> PICTUREPRODUCTs { get; set; }
        public DbSet<RFSERIAL> RFSERIALS { get; set; }
        public DbSet<SN_BAD728ULT> SN_BAD728ULT { get; set; }
        public DbSet<SN_MISSINGSERIALS_TEMP> SN_MISSINGSERIALS_TEMP { get; set; }
        public DbSet<STATS_LIVE_PROCESS_LOG> STATS_LIVE_PROCESS_LOG { get; set; }
        public DbSet<SUPPLIER_UPDATE> SUPPLIER_UPDATE { get; set; }
        public DbSet<TimeSheetFilterGroupHistory> TimeSheetFilterGroupHistories { get; set; }
        public DbSet<TS_PRD_DEP> TS_PRD_DEP { get; set; }
        public DbSet<TS_PRD_EMP> TS_PRD_EMP { get; set; }
        public DbSet<TS_PRDPRJ_LOG> TS_PRDPRJ_LOG { get; set; }
    }
}
