//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_CERTIFICATE_LOG
    {
        public int LOG_ID { get; set; }
        public string SOFT_SERIAL { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_USERNAME { get; set; }
        public string LOG_REMOTE_HOST { get; set; }
        public string LOG_REMOTE_ADDR { get; set; }
    }
}
