//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_REGISTRATION_DEMO
    {
        public int REG_ID { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string REG_EMAIL { get; set; }
        public string REG_PASSWORD { get; set; }
        public string REG_SYSFIRSTNAME { get; set; }
        public string REG_SYSLASTNAME { get; set; }
        public string REG_SYSCOMPAGNY { get; set; }
        public string REG_SYSADDR { get; set; }
        public string REG_SYSCITY { get; set; }
        public string REG_SYSSTATEPROV { get; set; }
        public string REG_SYSCOUNTRY { get; set; }
        public string REG_SYSPOSTALZIP { get; set; }
        public string REG_SYSTELEPHONE { get; set; }
        public string REG_SYSFAX { get; set; }
        public string REG_SYSEMAIL { get; set; }
    }
}
