//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_REGISTRATION_HISTORY
    {
        public int REGH_ID { get; set; }
        public int REG_ID { get; set; }
        public string REG_DIGIT8 { get; set; }
        public string REG_DIGIT16 { get; set; }
        public string REG_CODE { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public string REG_CONTACTNAME { get; set; }
        public string REG_EMAIL { get; set; }
        public string REG_REASON { get; set; }
        public string REG_SYSFIRSTNAME { get; set; }
        public string REG_SYSLASTNAME { get; set; }
        public string REG_SYSCOMPAGNY { get; set; }
        public string REG_SYSADDR { get; set; }
        public string REG_SYSCITY { get; set; }
        public string REG_SYSSTATEPROV { get; set; }
        public string REG_SYSCOUNTRY { get; set; }
        public string REG_SYSPOSTALZIP { get; set; }
        public string REG_SYSTELEPHONE { get; set; }
        public string REG_SYSFAX { get; set; }
        public string REG_SYSEMAIL { get; set; }
        public string REG_DEAFIRSTNAME { get; set; }
        public string REG_DEALASTNAME { get; set; }
        public string REG_DEACOMPAGNY { get; set; }
        public string REG_DEAADDR { get; set; }
        public string REG_DEACITY { get; set; }
        public string REG_DEASTATEPROV { get; set; }
        public string REG_DEACOUNTRY { get; set; }
        public string REG_DEAPOSTALZIP { get; set; }
        public string REG_DEATELEPHONE { get; set; }
        public string REG_DEAFAX { get; set; }
        public string REG_DEAEMAIL { get; set; }
        public bool REG_UPGRADE { get; set; }
        public Nullable<System.DateTime> REG_UPGRADE_DATE { get; set; }
        public Nullable<bool> REG_ISUPGRADE2 { get; set; }
        public string USR_LOGIN { get; set; }
        public string REG_COMMENTS { get; set; }
        public Nullable<System.DateTime> REG_DATE_SAVE { get; set; }
        public string REG_OLD_VERSION { get; set; }
    }
}
