//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_SERIAL_FOR_PRINTER_ACCESS
    {
        public int NE_ID { get; set; }
        public string NE_SERIAL { get; set; }
    }
}
