//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_SERIAL
    {
        public int NE_ID { get; set; }
        public string NE_TYPE { get; set; }
        public string NE_VERSION { get; set; }
        public string NE_SERIAL1 { get; set; }
        public string NE_EDITION { get; set; }
        public Nullable<System.DateTime> NE_DATE_CREATED { get; set; }
        public bool NE_ACTIVITY { get; set; }
        public bool NE_PRINTED { get; set; }
        public Nullable<bool> NE_PANELUPGRADE { get; set; }
        public string NE_BARCODE { get; set; }
        public Nullable<int> NE_SN_USED { get; set; }
    }
}
