//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_VERSION
    {
        public int NE_VERSION_ID { get; set; }
        public string NE_VERSION_TYPE { get; set; }
        public Nullable<double> NE_VERSION1 { get; set; }
        public Nullable<int> BUILD { get; set; }
        public Nullable<System.DateTime> NE_VERSION_DATE { get; set; }
    }
}
