//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCINVENTORY
    {
        public int PC_ID { get; set; }
        public string PC_SNUM { get; set; }
        public string PC_PONUM { get; set; }
        public int OPERSYS_ID { get; set; }
        public int COMPGEN_ID { get; set; }
        public string PC_DOMWG { get; set; }
        public string PC_IP { get; set; }
        public string PC_NAME { get; set; }
        public string PC_VIDEO_CARD { get; set; }
        public string PC_SOUND_CARD { get; set; }
        public string PC_MOTHERBOARD { get; set; }
        public string PC_CDROM { get; set; }
        public string PC_CPU { get; set; }
        public string PC_HDD { get; set; }
        public string PC_MEMORY { get; set; }
        public string PC_NETW_ADAP { get; set; }
        public string PC_ANTIVIRUS { get; set; }
        public string TECH_USR { get; set; }
        public int EMP_ID { get; set; }
        public bool PC_DHCP { get; set; }
        public string PC_PHONEPLATE { get; set; }
        public string PC_PHONEPORT { get; set; }
        public string PC_NETPLATE { get; set; }
        public string PC_NETSWITCH { get; set; }
    }
}
