//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedometer_groups
    {
        public Pedometer_groups()
        {
            this.Pedometers = new HashSet<Pedometer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Pedometer> Pedometers { get; set; }
    }
}
