//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedometer
    {
        public Pedometer()
        {
            this.pedometer_users = new HashSet<pedometer_users>();
        }
    
        public int id { get; set; }
        public string serial { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> group_id { get; set; }
        public System.DateTime datecreated { get; set; }
    
        public virtual Pedometer_groups Pedometer_groups { get; set; }
        public virtual ICollection<pedometer_users> pedometer_users { get; set; }
    }
}
