//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedometer_user_data
    {
        public int id { get; set; }
        public int pedometer_user_id { get; set; }
        public int nbpas { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
