//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedometer_users
    {
        public int id { get; set; }
        public int pedometerId { get; set; }
        public string psw { get; set; }
    
        public virtual Pedometer Pedometer { get; set; }
    }
}
