//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTUREGROUP
    {
        public int PictureGroupID { get; set; }
        public string PictureGroupDescription { get; set; }
        public Nullable<int> PictureProductCount { get; set; }
    }
}
