//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTURE
    {
        public int PictureID { get; set; }
        public Nullable<int> PictureProductID { get; set; }
        public string PictureDesc { get; set; }
        public Nullable<int> PictureOrder { get; set; }
        public string PicturePath { get; set; }
        public Nullable<int> PictureWidth { get; set; }
        public Nullable<int> PictureHeight { get; set; }
        public string PictureText { get; set; }
        public Nullable<bool> LineBreakAfter { get; set; }
        public string PictureDescFR { get; set; }
    }
}
