//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROTOCOL_REQUEST
    {
        public int REQUEST_ID { get; set; }
        public string REQUEST_IP_REMOTE { get; set; }
        public string REQUEST_EMAIL { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public string REQUEST_FIRSTNAME { get; set; }
        public string REQUEST_LASTNAME { get; set; }
        public string REQUEST_COMPANY { get; set; }
        public string REQUEST_TITLE { get; set; }
        public string REQUEST_ADDRESS { get; set; }
        public string REQUEST_CITY { get; set; }
        public string REQUEST_STATE { get; set; }
        public string REQUEST_COUNTRY { get; set; }
        public string REQUEST_ZIP { get; set; }
        public string REQUEST_PHONE { get; set; }
        public string REQUEST_FAX { get; set; }
        public string REQUEST_MOBILEPHONE { get; set; }
        public Nullable<bool> REQUEST_ACTIVITY { get; set; }
        public Nullable<bool> REQUEST_ISTREATED { get; set; }
        public string REQUEST_PASSWORD { get; set; }
        public string REQUEST_REASON { get; set; }
        public Nullable<int> DI_ID_TMP { get; set; }
        public Nullable<int> DI_ID { get; set; }
        public string REQUEST_CASENUMBER { get; set; }
    }
}
