//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROTOCOL_PRODUCT
    {
        public PROTOCOL_PRODUCT()
        {
            this.PROTOCOL_PRODUCT_FILE = new HashSet<PROTOCOL_PRODUCT_FILE>();
        }
    
        public int PRODUCT_ID { get; set; }
        public Nullable<System.DateTime> PRODUCT_DATE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<bool> PRODUCT_ACTIVITY { get; set; }
    
        public virtual ICollection<PROTOCOL_PRODUCT_FILE> PROTOCOL_PRODUCT_FILE { get; set; }
    }
}
