//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROTOCOL_PRODUCT_FILE
    {
        public int FILE_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<System.DateTime> FILE_DATE { get; set; }
        public Nullable<bool> FILE_ACTIVITY { get; set; }
        public string FILE_URL { get; set; }
    
        public virtual PROTOCOL_PRODUCT PROTOCOL_PRODUCT { get; set; }
    }
}
