//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_CENTER
    {
        public int PT_CENTER_ID { get; set; }
        public string PT_CENTER_NAME { get; set; }
        public string PT_CENTER_NAME_FR { get; set; }
        public Nullable<int> PT_CENTER_RIGHT { get; set; }
        public Nullable<int> PT_CENTER_ORDER { get; set; }
        public bool PT_CENTER_ACTIVE { get; set; }
    }
}
