//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_PRODUCT_GROUP
    {
        public int PT_PRODUCT_GROUP_ID { get; set; }
        public Nullable<int> PT_PRODUCT_GROUP_PL_ID { get; set; }
        public Nullable<int> PT_PRODUCT_GROUP_RIGHT { get; set; }
        public Nullable<int> PT_PRODUCT_GROUP_DISTRIBUTOR { get; set; }
        public Nullable<int> PT_PRODUCT_GROUP_ICON { get; set; }
        public string PT_PRODUCT_GROUP_NAME_EN { get; set; }
        public string PT_PRODUCT_GROUP_NAME_FR { get; set; }
        public string PT_PRODUCT_GROUP_LINK_EN { get; set; }
        public string PT_PRODUCT_GROUP_LINK_FR { get; set; }
        public Nullable<int> PT_PRODUCT_GROUP_ORDER { get; set; }
        public bool PT_PRODUCT_GROUP_ACTIVE { get; set; }
    }
}
