//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_PRODUCT_LINE
    {
        public int PT_PRODUCT_LINE_ID { get; set; }
        public Nullable<int> PT_PRODUCT_LINE_RIGHT { get; set; }
        public Nullable<int> PT_PRODUCT_LINE_CENTER { get; set; }
        public Nullable<int> PT_PRODUCT_LINE_ICON { get; set; }
        public string PT_PRODUCT_LINE_LOGO { get; set; }
        public string PT_PRODUCT_LINE_NAME_EN { get; set; }
        public string PT_PRODUCT_LINE_NAME_FR { get; set; }
        public string PT_PRODUCT_LINE_SUB_NAME_EN { get; set; }
        public string PT_PRODUCT_LINE_SUB_NAME_FR { get; set; }
        public string PT_PRODUCT_LINE_MAIN_LINK_EN { get; set; }
        public string PT_PRODUCT_LINE_MAIN_LINK_FR { get; set; }
        public string PT_PRODUCT_LINE_LINK_EN { get; set; }
        public string PT_PRODUCT_LINE_LINK_FR { get; set; }
        public Nullable<int> PT_PRODUCT_LINE_ORDER { get; set; }
        public bool PT_PRODUCT_LINE_ACTIVE { get; set; }
    }
}
