//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_PRODUCT
    {
        public int PT_PRODUCT_ID { get; set; }
        public Nullable<int> PT_PRODUCT_PG_ID { get; set; }
        public Nullable<int> PT_PRODUCT_RIGHT { get; set; }
        public string PT_PRODUCT_ICON { get; set; }
        public string PT_PRODUCT_NAME_EN { get; set; }
        public string PT_PRODUCT_NAME_FR { get; set; }
        public string PT_PRODUCT_LINK_EN { get; set; }
        public string PT_PRODUCT_LINK_FR { get; set; }
        public Nullable<int> PT_PRODUCT_ORDER { get; set; }
        public bool PT_PRODUCT_ACTIVE { get; set; }
    }
}
