//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_NOTIFICATION_PRODUCTION_PRODUCT
    {
        public int ID { get; set; }
        public Nullable<int> DI_ID { get; set; }
        public string PRODUCT { get; set; }
        public string DISTRIBUTION { get; set; }
        public Nullable<int> SEARCH_CONDITION { get; set; }
        public bool NOTIFIED { get; set; }
        public Nullable<System.DateTime> LAST_NOTIFIED { get; set; }
        public string COMMENTS { get; set; }
    }
}
