//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_LOG_DELETE_NOT_CONFIRMED
    {
        public int LOG_ID { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_USR { get; set; }
        public string LOG_PASSWORD { get; set; }
        public string LOG_FIRSTNAME { get; set; }
        public string LOG_LASTNAME { get; set; }
        public string LOG_EMAIL { get; set; }
        public Nullable<System.DateTime> LOG_DATE_REQUEST_LOGIN { get; set; }
        public string LOG_DISTRIBUTOR_NAME { get; set; }
    }
}
