//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIALNUMBER_PRODUCTLIST
    {
        public int SN_PRODUCT_ID { get; set; }
        public string SN_PRODUCT_CODE { get; set; }
        public string SN_PRODUCT_SN { get; set; }
        public bool SN_PRODUCT_NOTICE { get; set; }
        public string SN_PRODUCT_CHILD_PREFIX { get; set; }
    }
}
