//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SN_QUEUE
    {
        public long SN_ID { get; set; }
        public Nullable<double> PRD_NO_INT { get; set; }
        public string PRD_NO { get; set; }
        public string SN { get; set; }
        public string DPROLOGNO { get; set; }
        public string CST_NO { get; set; }
        public string CST_NAME { get; set; }
        public string SN2 { get; set; }
        public string REV_NO { get; set; }
        public Nullable<double> ORD_ID { get; set; }
        public string VERSION { get; set; }
        public string SOFT_DESC { get; set; }
        public string BOXID { get; set; }
        public bool IS_TRANSFER { get; set; }
        public Nullable<long> TRANSFER_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int DI_ID { get; set; }
        public string DI_NAME { get; set; }
        public Nullable<System.DateTime> SN_DATE { get; set; }
        public string LINE { get; set; }
        public bool COPYING { get; set; }
    }
}
