//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATS_LIVE_PROCESS_LOG
    {
        public int web_invoice_id { get; set; }
        public int grp_id { get; set; }
        public string grp_name { get; set; }
        public int di_id { get; set; }
        public string di_name { get; set; }
        public string di_code { get; set; }
        public int prd_id { get; set; }
        public string prd_code { get; set; }
        public string prd_name { get; set; }
        public string item_code { get; set; }
        public int prd_stat { get; set; }
        public string periode { get; set; }
        public int qty { get; set; }
        public double prd_price { get; set; }
        public double usd { get; set; }
        public int qty_pack { get; set; }
        public double usd_pack { get; set; }
        public string item_issample { get; set; }
        public System.DateTime Process_Date { get; set; }
    }
}
