//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public int SUP_ID { get; set; }
        public bool SUP_ACTIVITY { get; set; }
        public string SUP_NAME { get; set; }
        public string SUP_AD1 { get; set; }
        public string SUP_AD2 { get; set; }
        public string SUP_AD3 { get; set; }
        public string SUP_ZC { get; set; }
        public string SUP_CTRY { get; set; }
        public string SUP_PHONE { get; set; }
        public string SUP_FAX { get; set; }
        public string SUP_ATT { get; set; }
        public string SUP_EMAIL { get; set; }
        public string SUP_CUR { get; set; }
        public Nullable<System.DateTime> SUP_OPENEND { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
    }
}
