//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_MAILINGLIST
    {
        public int SURVEY_ID { get; set; }
        public int ML_ID { get; set; }
        public int GRP_ID { get; set; }
        public int DI_ID { get; set; }
        public int USR_ID { get; set; }
        public int DEA_ID { get; set; }
        public int SURVEY_1 { get; set; }
        public int SURVEY_2 { get; set; }
        public string SURVEY_3 { get; set; }
    }
}
