//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_1
    {
        public int SURVEY_ID { get; set; }
        public Nullable<int> USR_ID { get; set; }
        public Nullable<bool> SURVEY_1_DONE { get; set; }
        public Nullable<bool> SURVEY_1_NA { get; set; }
        public Nullable<int> SURVEY_1_1 { get; set; }
        public Nullable<int> SURVEY_1_2 { get; set; }
        public Nullable<int> SURVEY_1_3 { get; set; }
        public Nullable<int> SURVEY_1_4 { get; set; }
        public Nullable<int> SURVEY_1_5 { get; set; }
        public string SURVEY_1_6 { get; set; }
        public string SURVEY_1_7 { get; set; }
        public string SURVEY_1_8 { get; set; }
        public Nullable<int> SURVEY_1_9 { get; set; }
        public Nullable<int> SURVEY_1_10 { get; set; }
        public Nullable<int> SURVEY_1_11 { get; set; }
    }
}
