//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_DISTRIBUTOR_QUESTION
    {
        public int QUESTION_ID { get; set; }
        public string QUESTION_NO { get; set; }
        public string ANSWER_VALUE { get; set; }
        public string QUESTION_SECTION { get; set; }
        public string QUESTION_QUESTION { get; set; }
        public string QUESTION_SUBQUESTION { get; set; }
        public string ANSWER_ANSWER { get; set; }
    }
}
