//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAX
    {
        public int TAXES_ID { get; set; }
        public string TAXES_PROVINCE { get; set; }
        public Nullable<double> TAXES_FEDERAL { get; set; }
        public Nullable<double> TAXES_PROVINCIAL { get; set; }
    }
}
