//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetTracking
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int EMP_ID { get; set; }
        public System.DateTime DTStart { get; set; }
        public System.DateTime DTEnd { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual TimeSheetProject TimeSheetProject { get; set; }
    }
}
