//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetProject
    {
        public TimeSheetProject()
        {
            this.TimeSheetTrackings = new HashSet<TimeSheetTracking>();
            this.TimeSheetUserProjectLinks = new HashSet<TimeSheetUserProjectLink>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int GroupID { get; set; }
        public int CreatorEmpID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<TimeSheetTracking> TimeSheetTrackings { get; set; }
        public virtual ICollection<TimeSheetUserProjectLink> TimeSheetUserProjectLinks { get; set; }
    }
}
