//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_EXPENSES
    {
        public int EXP_ID { get; set; }
        public int MP_ID { get; set; }
        public System.DateTime EXP_DATE { get; set; }
        public string EXP_DESCRIPTION { get; set; }
        public double EXP_AMOUNT { get; set; }
        public string EXP_INVOICE { get; set; }
    }
}
