//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_EXACT_SUBMIT
    {
        public int SUBMIT_ID { get; set; }
        public Nullable<int> TPD_NO { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<bool> SUBMIT_PAYROLL { get; set; }
        public string TPD_ADP_PERIOD_WEEK1 { get; set; }
        public string TPD_ADP_PERIOD_WEEK2 { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
    }
}
