//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_MASTERPRJ
    {
        public TS_MASTERPRJ()
        {
            this.DEPARTMENTs = new HashSet<DEPARTMENT>();
        }
    
        public int MP_ID { get; set; }
        public int DEP_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> ST_ID { get; set; }
        public string MP_CODE { get; set; }
        public string MP_DESCRIP { get; set; }
        public string MP_DETAILSDESCRIP { get; set; }
        public Nullable<System.DateTime> MP_DUEDATE { get; set; }
        public Nullable<System.DateTime> MP_ESTIMDATE { get; set; }
        public Nullable<int> MP_COMPLETE { get; set; }
        public Nullable<System.DateTime> MP_DATECOMPLETE { get; set; }
        public string MP_HOURSWORKED { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual TS_STATUS TS_STATUS { get; set; }
        public virtual ICollection<DEPARTMENT> DEPARTMENTs { get; set; }
    }
}
