//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_PAYROLL
    {
        public int PAYROLL_ID { get; set; }
        public string EMP_LASTNAME { get; set; }
        public string EMP_FIRSTNAME { get; set; }
        public System.DateTime TS_DATE { get; set; }
        public Nullable<System.DateTime> TPC_IN_REAL1 { get; set; }
        public Nullable<System.DateTime> TPC_OUT_REAL1 { get; set; }
        public Nullable<System.DateTime> TPC_IN_REAL2 { get; set; }
        public Nullable<System.DateTime> TPC_OUT_REAL2 { get; set; }
        public Nullable<System.DateTime> TPC_IN_REAL3 { get; set; }
        public Nullable<System.DateTime> TPC_OUT_REAL3 { get; set; }
        public Nullable<System.DateTime> TPC_IN_REAL4 { get; set; }
        public Nullable<System.DateTime> TPC_OUT_REAL4 { get; set; }
    }
}
