//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_PUNCH
    {
        public int TPC_ID { get; set; }
        public int EMP_ID { get; set; }
        public Nullable<int> PAYROLL_ID { get; set; }
        public Nullable<int> TPD_NO { get; set; }
        public System.DateTime TS_DATE { get; set; }
        public Nullable<System.DateTime> TPC_IN { get; set; }
        public Nullable<System.DateTime> TPC_OUT { get; set; }
        public int TR_ID { get; set; }
        public Nullable<System.DateTime> TPC_IN_REAL1 { get; set; }
        public Nullable<System.DateTime> TPC_IN_REAL2 { get; set; }
        public Nullable<System.DateTime> TPC_IN_REAL3 { get; set; }
        public Nullable<System.DateTime> TPC_OUT_REAL1 { get; set; }
        public Nullable<System.DateTime> TPC_OUT_REAL2 { get; set; }
        public Nullable<System.DateTime> TPC_OUT_REAL3 { get; set; }
        public bool TPC_LUNCH { get; set; }
        public bool TPC_SOUPER { get; set; }
        public Nullable<System.DateTime> TPC_HIN { get; set; }
        public Nullable<System.DateTime> TPC_HOUT { get; set; }
        public Nullable<int> TR_ID1 { get; set; }
        public Nullable<double> TPC_TOTAL { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
