//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_PRODUCT
    {
        public int PRD_ID { get; set; }
        public string PRD_CODE { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string PRD_DESC { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
    }
}
