//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_PRDPRJ_LOG
    {
        public int LOG_ID { get; set; }
        public string PRD_ID { get; set; }
        public string PRJ_ID { get; set; }
        public string EVENT { get; set; }
        public string EMPLOYEE { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
    }
}
