//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_STATUS
    {
        public TS_STATUS()
        {
            this.TS_MASTERPRJ = new HashSet<TS_MASTERPRJ>();
        }
    
        public int ST_ID { get; set; }
        public string ST_NAME { get; set; }
    
        public virtual ICollection<TS_MASTERPRJ> TS_MASTERPRJ { get; set; }
    }
}
