//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TIMESHEET
    {
        public int TS_ID { get; set; }
        public Nullable<int> TPC_ID { get; set; }
        public int EMP_ID { get; set; }
        public Nullable<int> PRD_ID { get; set; }
        public Nullable<int> TASKS_ID { get; set; }
        public int MP_ID { get; set; }
        public Nullable<int> TP_ID { get; set; }
        public int TK_ID { get; set; }
        public System.DateTime TS_DATE { get; set; }
        public int TPD_NO { get; set; }
        public string TS_NOTE { get; set; }
        public Nullable<double> TS_TIME { get; set; }
        public Nullable<int> TS_TIME_MIN { get; set; }
        public Nullable<bool> TS_FOR_INNO { get; set; }
    }
}
