//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_TIMEGRP
    {
        public int TGR_ID { get; set; }
        public string TGR_NAME { get; set; }
        public System.DateTime TGR_BEGIN { get; set; }
        public System.DateTime TGR_END { get; set; }
        public bool TGR_LUNCH { get; set; }
        public bool TGR_SOUPER { get; set; }
        public bool TGR_SUNDAY { get; set; }
        public bool TGR_MONDAY { get; set; }
        public bool TGR_TUESDAY { get; set; }
        public bool TGR_WEDNESDAY { get; set; }
        public bool TGR_THURSDAY { get; set; }
        public bool TGR_FRIDAY { get; set; }
        public bool TGR_SATURDAY { get; set; }
        public string TGR_TYPE { get; set; }
        public string NS_INTERNALID { get; set; }
    }
}
