//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_IMPERIAL
    {
        public int USER_ID { get; set; }
        public Nullable<int> DI_ID { get; set; }
        public string USER_LOGIN { get; set; }
        public string USER_PWD { get; set; }
        public string USER_FIRSTNAME { get; set; }
        public string USER_LASTNAME { get; set; }
        public string USER_CONTACT { get; set; }
        public string USER_COMPANY { get; set; }
        public string USER_ADDRESS { get; set; }
        public string USER_CITY { get; set; }
        public string USER_STATE { get; set; }
        public Nullable<int> CTRY_ID { get; set; }
        public string USER_ZIP { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_PHONE { get; set; }
        public Nullable<System.DateTime> USER_OPENED { get; set; }
        public Nullable<bool> USER_IS_ACTIVE { get; set; }
        public Nullable<bool> USER_IS_DELETED { get; set; }
        public string USER_IMPERIAL_CONFIRM_CODE { get; set; }
        public Nullable<bool> USER_IS_CONFIRMED { get; set; }
    }
}
