//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP_CONFERENCE_2003_FRIEND
    {
        public int VIP_FRIEND_ID { get; set; }
        public Nullable<int> VIP_ID { get; set; }
        public string VIP_FRIENDFIRSTNAME { get; set; }
        public string VIP_FRIENDLASTNAME { get; set; }
    
        public virtual VIP_CONFERENCE_2003 VIP_CONFERENCE_2003 { get; set; }
    }
}
