//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP_CONFERENCE_2003
    {
        public VIP_CONFERENCE_2003()
        {
            this.VIP_CONFERENCE_2003_FRIEND = new HashSet<VIP_CONFERENCE_2003_FRIEND>();
        }
    
        public int VIP_ID { get; set; }
        public Nullable<int> DI_ID { get; set; }
        public string VIP_USR { get; set; }
        public Nullable<bool> VIP_REGISTER { get; set; }
        public string VIP_FIRSTNAME { get; set; }
        public string VIP_LASTNAME { get; set; }
        public string VIP_EMAIL { get; set; }
        public Nullable<System.DateTime> VIP_LASTCHANGE { get; set; }
        public Nullable<int> VIP_NUMBERATTENDEES { get; set; }
        public string VIP_AIRLINE { get; set; }
        public string VIP_FLIGHTNUMBER { get; set; }
        public Nullable<System.DateTime> VIP_ARRIVALDATE { get; set; }
        public Nullable<System.DateTime> VIP_ARRIVALTIME { get; set; }
        public Nullable<System.DateTime> VIP_DEPARTUREDATE { get; set; }
        public Nullable<System.DateTime> VIP_DEPARTURETIME { get; set; }
        public Nullable<int> VIP_NUMBEROFROOMS { get; set; }
        public string VIP_OCCUPATION { get; set; }
        public Nullable<bool> VIP_SHARINGROOM { get; set; }
        public Nullable<bool> VIP_SMOKING { get; set; }
    
        public virtual ICollection<VIP_CONFERENCE_2003_FRIEND> VIP_CONFERENCE_2003_FRIEND { get; set; }
    }
}
