//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBDISUSER
    {
        public int DI_ID { get; set; }
        public int USR_ID { get; set; }
        public string USR_USR { get; set; }
        public string USR_PASSWORD { get; set; }
        public string USR_FIRSTNAME { get; set; }
        public string USR_LASTNAME { get; set; }
        public string USR_ATT { get; set; }
        public System.DateTime USR_OPENED { get; set; }
        public Nullable<System.DateTime> USR_EXPIRED { get; set; }
        public string USR_EMAIL { get; set; }
        public string USR_LANGUAGE { get; set; }
        public bool USR_ACTIVITY { get; set; }
        public Nullable<bool> USR_IS_DELETED { get; set; }
        public bool USR_CHECKTMPDEA { get; set; }
        public bool USR_CHECKORDDEA { get; set; }
        public bool USR_CHECKSUBS { get; set; }
        public System.DateTime USR_LASTACTIVITY { get; set; }
        public int USR_COMENBR { get; set; }
        public string USR_ADDRESS { get; set; }
        public string USR_CITY { get; set; }
        public string USR_STATE { get; set; }
        public string CTRY_NO { get; set; }
        public string USR_ZC { get; set; }
        public string USR_PHONE { get; set; }
        public string USR_FAX { get; set; }
        public string USR_BUSINESSCELLULAR { get; set; }
        public string USR_BUSINESSPHONE { get; set; }
        public string USR_BUSINESSFAX { get; set; }
        public string USR_BUSINESSOTHERPHONE { get; set; }
        public string USR_BUSINESSEMAIL { get; set; }
        public string USR_PERSONNALCELLULAR { get; set; }
        public string USR_PERSONNALPHONE { get; set; }
        public string USR_PERSONNALFAX { get; set; }
        public string USR_PERSONNALOTHERPHONE { get; set; }
        public string USR_PERSONNALEMAIL { get; set; }
        public bool USR_MASTER { get; set; }
        public Nullable<bool> USR_POSITION_ORDER { get; set; }
        public bool USR_CANORDER { get; set; }
        public Nullable<bool> USR_ORDER_BAHAMAS { get; set; }
        public Nullable<bool> USR_WEB_PARADOX { get; set; }
        public Nullable<bool> USR_WEB_POSITION { get; set; }
        public Nullable<bool> USR_ISACCESSSN { get; set; }
        public Nullable<bool> USR_ISMARKETING { get; set; }
        public Nullable<bool> USR_ISTECHNOTES { get; set; }
        public Nullable<bool> USR_ISPRICELIST { get; set; }
        public int USR_TYPE { get; set; }
        public int USR_SITE_ACCESS { get; set; }
        public int USR_OLO_ACCESS { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual DISTRIBUTOR DISTRIBUTOR { get; set; }
    }
}
