//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBTECHSUPP
    {
        public int TS_ID { get; set; }
        public System.DateTime TS_DATETIME { get; set; }
        public string TS_NAME { get; set; }
        public string TS_COMPANY { get; set; }
        public string TS_EMAIL { get; set; }
        public string TS_CTRY { get; set; }
        public string TS_SUPPLIER { get; set; }
        public string TS_PHONE { get; set; }
        public string TS_FAX { get; set; }
        public string TS_CONTROLPANEL { get; set; }
        public string TS_KEYPAD { get; set; }
        public string TS_DETECTOR { get; set; }
        public string TS_SOFTWARE { get; set; }
        public string TS_ACCESSORIES { get; set; }
        public string TS_EXPMOD { get; set; }
        public string TS_PROBLEM { get; set; }
        public string TS_USR { get; set; }
    }
}
